generic improvements for the testsbed
* fix run-tests so it can return != 0
* bail out if prepare fails
* add more sanity checks to prepare
* generalize usb-ids, paths
* add test for flashing from application mode
* add test reading simcards via pysim

Change-Id: I246224e29e5936b4fe40cf7d7a5ff83c9940d121

diff --git a/tests/sysmo-octsim/run-tests b/tests/sysmo-octsim/run-tests
--- a/tests/sysmo-octsim/run-tests
+++ b/tests/sysmo-octsim/run-tests
@@ -1,7 +1,7 @@
 #!/bin/sh
 
 # default: execute all tests
-TESTS="01_check_rig.sh 02_flash_dfu.sh 03_check_lsusb.sh 04_check_dfu_lsusb.sh"
+TESTS="01_check_rig.sh 02_flash_dfu.sh 03_check_lsusb.sh 04_check_dfu_lsusb.sh 05_flash_dfu_from_app.sh 06_test_simcards.sh"
 
 # if command line specifies some specific tests, execute only those
 if [ $# -ge 1 ]; then
@@ -13,6 +13,12 @@ NUM_FAIL=0
 
 # prepare test card
 ./prepare
+if [ $? -eq 0 ]; then
+	echo "Prepare done"
+else
+        echo "Prepare Test FAILED!"
+	exit 2
+fi
 
 for T in $TESTS; do
 	echo "==> Executing Testcase $T"
